import { useRef, useState } from 'react';
import data from './demo.json';
type Stage = typeof data.workflow_stages[number];
const chapters = ['Observe','Explain','Test','Learn'];
const descriptions = [
  ['Watch without knowing the ending.','The reviewer sees chronological frames and transcript prefixes. It records confusion before the full-story diagnosis.'],
  ['Make one small, testable edit.','The director proposes removing A’s silent ending. It must preserve the measurement explanation and the real bridge payoff.'],
  ['The render is only the beginning.','Mechanical checks confirm the intended trim. A fresh review then compares C with both inputs in both presentation orders.'],
  ['Keep the original when the gain is uncertain.','C does not reliably beat A on pacing or payoff. The system retains A and records the inconclusive experiment.'],
];
function Trace({stage,depth=0}:{stage:Stage;depth?:number}) {
 const children=data.workflow_stages.filter(s=>s.parent_id===stage.id);
 const label=<><span className="trace-name">{stage.title}</span><span className="trace-time">{((stage.duration_ms??0)/1000).toFixed(2)}s</span></>;
 return children.length ? <details className="trace-node" open={depth===0}><summary>{label}</summary><div className="trace-children">{children.map(s=><Trace key={s.id} stage={s} depth={depth+1}/>)}</div><a className="trace-link" href={stage.weave_url??data.weave_url} target="_blank" rel="noreferrer">Open this step in Weave ↗</a></details> : <div className="trace-leaf">{label}<a href={stage.weave_url??data.weave_url} target="_blank" rel="noreferrer" aria-label={`Open ${stage.title} in Weave`}>↗</a></div>;
}
export default function App(){
 const [chapter,setChapter]=useState(0),[version,setVersion]=useState('A'),[started,setStarted]=useState(false);
 const player=useRef<HTMLVideoElement>(null);const media=data.versions.find(v=>v.label===version)!;
 function selectChapter(i:number){setChapter(i);setVersion(i===2?'C':'A');setStarted(false);}
 return <><header className="topbar"><a className="wordmark" href="#"><span className="brand-mark" aria-hidden="true"><i/><i/></span>DIRECTORLOOP</a><nav className="nav" aria-label="Primary"><a className="nav-link" href="#experiment">The experiment</a><a className="nav-link" href="#evidence">Trace evidence</a><a className="nav-link" href="#tools">Built with</a></nav><span className="mode-flag">RECORDED DEMO</span></header>
 <main className="demo-main"><section className="demo-hero"><p className="eyebrow">A video editing agent that tests its own edits</p><h1>The edit has to<br/><span>earn its place.</span></h1><p>Observe. Explain. Test. Keep only what holds up.</p><a href="#experiment" className="btn btn-primary">Explore a real run <span aria-hidden="true">↘</span></a><a href={data.weave_url} target="_blank" rel="noreferrer" className="hero-trace">Open W&B Weave ↗</a></section>
 <section id="experiment" className="demo-experiment"><div className="demo-section-head"><div><p className="eyebrow">The Smoot experiment</p><h2>One idea. Three versions.</h2></div><span className="recorded-label">Saved September 12, 2026 · 93.2s run</span></div>
 <div className="demo-workspace"><div className="demo-video"><div className="version-selector" role="group" aria-label="Video version">{data.versions.map(v=><button key={v.label} onClick={()=>{setVersion(v.label);setStarted(false)}} aria-pressed={v.label===version}>{v.label}<small>{(v.duration_ms/1000).toFixed(1)}s</small></button>)}</div><div className="media-wrap"><video ref={player} key={media.src} src={media.src} poster={media.poster} controls playsInline preload="metadata" onPlay={()=>setStarted(true)}/>{!started&&<button className="play-overlay" aria-label={`Play version ${version}`} onClick={()=>void player.current?.play().catch(()=>{})}><span aria-hidden="true">▶</span></button>}</div><p className="video-caption">{version==='A'?'A · Original, retained':version==='B'?'B · Faster alternative':'C · Agent’s trimmed candidate'}</p></div>
 <div className="demo-story"><nav className="chapter-nav" aria-label="Experiment chapters">{chapters.map((c,i)=><button key={c} onClick={()=>selectChapter(i)} className={chapter===i?'is-active':''} aria-current={chapter===i?'step':undefined}><span>0{i+1}</span>{c}</button>)}</nav><p className="eyebrow">{chapter===0?'Cold audience review':chapter===1?'A constrained hypothesis':chapter===2?'Independent checks':'The actual decision'}</p><h3>{descriptions[chapter][0]}</h3><p className="story-copy">{descriptions[chapter][1]}</p>
 {chapter===0&&<div className="evidence-card"><span className="evidence-type">MODEL JUDGMENT</span><h4>The final image stays after the story resolves.</h4><button className="time-link" onClick={()=>{if(player.current){player.current.currentTime=12;void player.current.play();}}}>Inspect A at 12.0s ↗</button><div className="beat-line"><span>Hook</span><span>Method</span><span>Reveal</span><span className="tail">Tail</span></div></div>}
 {chapter===1&&<div className="evidence-card"><span className="evidence-type">EDIT PLAN</span><div className="trim-diagram"><span>Keep A’s story</span><span>−1.11s tail</span></div><p>Preserve the opening, the marking step, the name reveal, and the real photograph.</p><button className="text-button" onClick={()=>selectChapter(2)}>See the rendered candidate →</button></div>}
 {chapter===2&&<div className="evidence-card"><span className="evidence-type">MECHANICAL CHECKS + MODEL JUDGMENT</span><div className="check-row"><span>Trim rendered as planned</span><b>Verified</b></div><div className="check-row"><span>Content protection checks</span><b>Passed</b></div><div className="check-row"><span>C vs A · target region</span><b>Same</b></div><div className="check-row"><span>C vs A · whole video</span><b className="warn">Unstable</b></div></div>}
 {chapter===3&&<div className="evidence-card decision-card"><span className="evidence-type">KEEP A</span><h4>A successful render is not proof of improvement.</h4><p>No reliable gain on pacing or payoff. The negative result stays in the record.</p><a href={data.weave_url} target="_blank" rel="noreferrer">Inspect the decision in Weave ↗</a></div>}
 <div className="chapter-controls"><span>{chapter+1} / 4</span><button className="btn" onClick={()=>selectChapter((chapter+1)%4)}>{chapter===3?'Back to observe':'Next: '+chapters[chapter+1]} →</button></div></div></div>
 <p className="honesty-note">Recorded execution, playable artifacts. These are fallible model judgments—not measured human retention or view predictions.</p></section>
 <section id="evidence" className="demo-evidence"><div className="demo-section-head"><div><p className="eyebrow">The agent at work</p><h2>Follow every decision.</h2></div><a className="btn" href={data.weave_url} target="_blank" rel="noreferrer">Whole session in Weave ↗</a></div><div className="run-stats"><div><b>39</b><span>model calls</span></div><div><b>60</b><span>recorded workflow steps</span></div><div><b>3</b><span>verified video artifacts</span></div><div><b>1</b><span>rejected candidate</span></div></div><details className="workflow-disclosure"><summary>Explore the connected workflow <span>Observe → repair → rejudge → compare → decide</span></summary><div className="trace-tree">{data.workflow_stages.filter(s=>!s.parent_id).map(s=><Trace key={s.id} stage={s}/>)}</div></details><p className="micro-note">The tree uses the original parent–child records. Weave links may require project access. <a href="/evidence.json" download>Download curated evidence</a>.</p></section>
 <section id="tools" className="demo-tools"><p className="eyebrow">How we used the ecosystem</p><h2>Compute, inspection,<br/><span>and evidence.</span></h2><div className="sponsor-grid"><article><span className="tool-number">01</span><h3>W&B Weave</h3><p>The audit trail: connected agent steps, model calls, timing, inputs, outputs, and decisions.</p><a href={data.weave_url} target="_blank" rel="noreferrer">Real session trace ↗</a></article><article><span className="tool-number">02</span><h3>W&B Inference</h3><p>A separate low-cost Qwen screening pilot: 3 videos, 9 requests, $0.0319 estimated usage. Quality limitations remain visible.</p><a href="https://wandb.ai/leondragon3798-curio/directorloop/r/call/01a09b5e-8b74-7bc8-8090-b919e0948d11" target="_blank" rel="noreferrer">Screening trace ↗</a></article><article><span className="tool-number">03</span><h3>marimo / Molab</h3><p>Interactive cloud GPU experiments with an open vision model. GPU smoke test completed; real-footage validation is a separate workstream.</p><a href="https://molab.marimo.io/notebooks/nb_cPf3k8sgetGjnpqJ3nrM8o" target="_blank" rel="noreferrer">GPU notebook ↗</a></article><article><span className="tool-number">04</span><h3>TypeSafe</h3><p>Structured judgment setup verified with a synthetic test. It is prepared for narrow evidence questions, not used in this A/B/C decision.</p><span className="tool-status">Integration preparation</span></article></div><div className="tool-foot"><span>OpenAI · vision review and edit planning in this run</span><span>FFmpeg + local Whisper · media and transcription</span><span>ARIA · potential run-analysis assistant, not part of this recorded execution</span></div></section>
 <footer className="demo-footer"><a className="wordmark" href="#">DIRECTORLOOP</a><p>Make a change. Test it. Keep the evidence.</p><span>Public read-only presentation · no paid analysis controls</span></footer></main></>;
}
