import { useEffect, useRef, useState } from 'react';
import liveConfig from './live-config.json';
export type Source = File | {src:string; name:string} | null;
type Observation={text:string;kind:string;frame_timestamps_ms:number[];asr_quote:string|null};
type Window={start_ms:number;end_ms:number;status:string;validation_issues:string[];weave_url?:string;judgment:null|{understanding:string;attention_risk:string;suggestion:string;uncertainties:string[];observations:Observation[]}};
type Report={status:string;model_calls:number;weave_url?:string;windows:Window[];error?:string;duration_ms:number};
type Event={seq:number;stage:string;message:string};
type Job={state:string;stage:string;elapsed_ms:number;error?:string};
const ENDPOINT=liveConfig.endpoint;
const terminal=(s:string)=>['COMPLETED','FAILED','CANCELED'].includes(s);
const trace=(url?:string)=>url?.startsWith('https://wandb.ai/')?url:undefined;
export default function LiveAnalysis({source,mode,onBusy}:{source:Source;mode:'single'|'ab';onBusy:(value:boolean)=>void}){
 const [busy,setBusy]=useState(false),[phase,setPhase]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<Report|null>(null),[job,setJob]=useState<Job|null>(null),[events,setEvents]=useState<Event[]>([]),[ids,setIds]=useState<{job_id:string;screen_id:string}|null>(null),[connected,setConnected]=useState<boolean|null>(null);
 const [analyzedName,setAnalyzedName]=useState('');
 useEffect(()=>onBusy(busy),[busy,onBusy]);
 const request=useRef<{source:Source;id:string}|null>(null);const panel=useRef<HTMLDivElement>(null);const session=useRef(crypto.randomUUID().replaceAll('-',''));
 useEffect(()=>{if(!ENDPOINT)return;void fetch(ENDPOINT+'/health').then(r=>r.json()).then(x=>setConnected(Boolean(x.available))).catch(()=>setConnected(false));},[]);
 async function api(path:string,init:RequestInit={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),init.method==='POST'?120000:20000);try{const response=await fetch(ENDPOINT+path,{...init,signal:controller.signal,headers:{'X-Demo-Session':session.current,...init.headers}});const body=await response.json().catch(()=>({detail:'The engine returned an unreadable response.'}));if(!response.ok)throw new Error(typeof body.detail==='string'?body.detail:'This request could not be completed.');return body;}catch(e){if(controller.signal.aborted)throw new Error('The connection timed out. Retry this same video to recover the existing submission safely.');throw e;}finally{clearTimeout(timeout);}}
 useEffect(()=>{if(!ids)return;let stopped=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const [next,ev,report]=await Promise.all([api('/jobs/'+ids!.job_id),api('/jobs/'+ids!.job_id+'/events'),api('/reports/'+ids!.screen_id).catch(()=>null)]);if(stopped)return;setJob(next);setEvents(ev);if(report)setResult(report);setError('');setPhase(terminal(next.state)?next.state==='COMPLETED'?'Review complete':next.state==='CANCELED'?'Analysis canceled':'Analysis stopped':ev.at(-1)?.message||'The engine is preparing this video.');if(terminal(next.state)){const finalReport=await api('/reports/'+ids!.screen_id).catch(()=>null);if(stopped)return;if(finalReport)setResult(finalReport);if(finalReport&&finalReport.status!=='running'||next.state!=='COMPLETED'){setBusy(false);return;}setPhase('Finishing the saved report');}}catch(e){if(stopped)return;setError(e instanceof Error?e.message:'Connection interrupted.');}if(!stopped)timer=setTimeout(poll,2000);}void poll();return()=>{stopped=true;clearTimeout(timer);};},[ids]);
 async function start(){if(!source||mode!=='single')return;if(!ENDPOINT){setError('Live analysis is not connected yet.');return;}setAnalyzedName(source.name);setBusy(true);setError('');setResult(null);setEvents([]);setJob(null);setIds(null);setPhase('Uploading your video');setTimeout(()=>panel.current?.scrollIntoView({behavior:'smooth',block:'start'}),50);
 try{let file:File;if(source instanceof File)file=source;else{const r=await fetch(source.src);if(!r.ok)throw new Error('The selected demo video is unavailable.');file=new File([await r.blob()],source.name,{type:'video/mp4'});}if(file.size>50*1024*1024)throw new Error('Live analysis supports files up to 50 MB.');if(request.current?.source!==source)request.current={source,id:crypto.randomUUID()};const form=new FormData();form.append('request_id',request.current.id);form.append('file',file);const response=await api('/analyze',{method:'POST',body:form});setPhase('Upload received. Waiting for the screening worker.');setIds(response);}catch(e){setError(e instanceof Error?e.message:'Analysis could not start.');setPhase('Analysis did not start');setBusy(false);}}
 async function cancel(){if(!ids)return;try{await api('/jobs/'+ids.job_id+'/cancel',{method:'POST'});setPhase('Cancellation requested. Waiting for the current step to finish.');}catch(e){setError(String(e));}}
 return <><div className="input-actions"><span className="muted">{mode==='ab'?'Live screening accepts one video. Explore the recorded A/B experiment below.':'Live screening · up to 3 AI calls · timestamped evidence and Weave trace'}</span><span className="input-buttons"><button className="btn btn-primary btn-hero" disabled={!source||mode!=='single'||busy} onClick={()=>void start()}>{busy?'Analyzing…':'Analyze video'}</button><a className="btn btn-quiet" href="#experiment">Explore a demo</a></span></div>{connected===false&&!busy&&<p className="live-note">The live engine is currently unavailable. The recorded experiment remains ready to explore.</p>}
 {(phase||error||result)&&<div className="live-analysis" ref={panel}><div className="live-analysis-head"><div><span className="eyebrow">{busy?'Live engine · W&B Inference':'Screening result'}</span><h2>{phase}</h2>{analyzedName&&<p className="live-source-name">Analysis of {analyzedName}</p>}</div>{job&&<span className="mono">{Number.isFinite(job.elapsed_ms)?(job.elapsed_ms/1000).toFixed(1)+'s':'In progress'}</span>}</div><p className="live-note">Frames and local transcript are reviewed in chronological prefixes. These are model suggestions; no human retention is measured and no edit is applied.</p>{error&&<div className="callout callout-bad" role="alert">{error}{ids&&<span> Progress will reconnect automatically; the analysis is not resubmitted.</span>}</div>}<div className="live-status" role="status" aria-live="polite">{busy?phase:result?.status==='needs_review'?'Review required: some evidence checks need attention.':job?.error||''}</div>{busy&&ids&&<button className="btn btn-small" onClick={()=>void cancel()}>Stop analysis</button>}
 {events.length>0&&<details className="live-progress" open={busy}><summary>Actual workflow progress · {events.length} events</summary><ol>{events.map(e=><li key={e.seq}><span className="mono">{String(e.seq).padStart(2,'0')}</span><span>{e.message||e.stage.replaceAll('_',' ').toLowerCase()}</span></li>)}</ol></details>}
 {result&&<><div className="live-result-meta"><span>{result.model_calls} model calls</span><span>{result.duration_ms>0?(result.duration_ms/1000).toFixed(1)+'s video':'Preparing media'}</span><span>Human review required</span>{trace(result.weave_url)&&<a href={trace(result.weave_url)} target="_blank" rel="noreferrer">Open live Weave trace ↗</a>}</div><div className="live-windows">{result.windows.map(w=><article className="live-window" key={w.end_ms}><div className="live-window-head"><span className="eyebrow">Prefix through {(w.end_ms/1000).toFixed(1)}s</span><span className={`window-state state-${w.status}`}>{w.status.replaceAll('_',' ')}</span></div>{w.judgment?<><h3>{w.judgment.understanding}</h3><p className="risk-label">Tentative attention risk: <b>{w.judgment.attention_risk}</b></p><ul>{w.judgment.observations.map((o,i)=><li key={i}><span className="observation-kind">{o.kind.replaceAll('_',' ')}</span><p>{o.text}</p><small>{o.frame_timestamps_ms.length>0?'Frames: '+o.frame_timestamps_ms.map(t=>(t/1000).toFixed(2)+'s').join(', '):''}{o.asr_quote?'Transcript: “'+o.asr_quote+'”':''}</small></li>)}</ul>{w.judgment.suggestion&&<p className="review-suggestion"><b>Review idea</b> {w.judgment.suggestion}</p>}{w.judgment.uncertainties.map((u,i)=><p className="live-note" key={i}>{u}</p>)}</>:<p className="live-note">{w.status==='pending'?'Waiting for this prefix.':'No validated model judgment was recorded for this prefix.'}</p>}{w.validation_issues.length>0&&<details><summary>Evidence checks · {w.validation_issues.length} issues</summary><ul>{w.validation_issues.map((v,i)=><li key={i}>{v}</li>)}</ul></details>}{trace(w.weave_url)&&<a className="text-link" href={trace(w.weave_url)} target="_blank" rel="noreferrer">Inspect this step ↗</a>}</article>)}</div></>}
 </div>}</>;
}
