import {useState} from 'react';
type Moment={start_ms:number;end_ms:number;status:string;validation_issues:string[];judgment:null|{attention_risk:string;suggestion:string}};
const shortReason=(text:string)=>text.split(/(?<=[.!?])\s+/).map(x=>x.trim()).find(x=>/[.!?]$/.test(x)&&x.length<=120&&x.split(/\s+/).length<=18)||'Review this moment before making a change.';
const seconds=(ms:number)=>Number((ms/1000).toFixed(1))+'s';
export default function RiskChart({windows,duration}:{windows:Moment[];duration:number}){
 const [selected,setSelected]=useState(0);const index=Math.min(selected,Math.max(0,windows.length-1));const chosen=windows[index];const total=Math.max(duration,...windows.map(x=>x.end_ms),1);const percent=(n:number)=>(n/total*100)+'%';
 const gaps:{start:number;end:number}[]=[];let cursor=0;for(const w of windows){if(w.start_ms>cursor)gaps.push({start:cursor,end:w.start_ms});cursor=Math.max(cursor,w.end_ms);}if(cursor<total)gaps.push({start:cursor,end:total});
 const y=(risk:string)=>({high:28,medium:82,low:136,unknown:181}[risk]??181);
 const label=(i:number)=>i===0?'Opening':i===windows.length-1?'Ending':'Middle';
 return <section className="risk-overview" aria-label="Sampled attention risk"><h3>Where viewers may lose interest</h3><p className="risk-intro">AI estimates from sampled moments.</p><div className="risk-plot"><div className="risk-axis" aria-hidden="true"><span className="risk-high">High</span><span className="risk-medium">Medium</span><span className="risk-low">Low</span><span className="risk-unknown">Unknown</span></div><div className="risk-graph"><svg width="100%" height="215" role="img" aria-label={'AI estimated attention risk. '+windows.map((w,i)=>label(i)+' '+seconds(w.start_ms)+' to '+seconds(w.end_ms)+': '+(w.judgment?.attention_risk??'unknown')).join('. ')}><defs><pattern id="unreviewed" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M0 8L8 0" stroke="#322e24" strokeWidth="1"/></pattern></defs>{[28,82,136,181].map(row=><line key={row} x1="0" x2="100%" y1={row} y2={row} stroke="#332e24" strokeDasharray="3 5"/>)}{gaps.map(g=><g key={g.start}><rect x={percent(g.start)} y="8" width={percent(g.end-g.start)} height="183" fill="url(#unreviewed)"/>{(g.end-g.start)/total>.2&&<text x={percent((g.start+g.end)/2)} y="106" textAnchor="middle" fill="#a59c8a" fontSize="11">Not reviewed</text>}</g>)}{windows.map((w,i)=><g key={w.end_ms} role="button" tabIndex={0} aria-label={label(i)+' '+seconds(w.start_ms)+' to '+seconds(w.end_ms)} onClick={()=>setSelected(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSelected(i)}}}><rect className="risk-segment" x={percent(w.start_ms)} y={y(w.judgment?.attention_risk??'unknown')-7} width={percent(w.end_ms-w.start_ms)} height="14" rx="4" fill={w.judgment?'#b3976e':'#605949'} stroke={i===index?'#f1d7aa':'#b3976e'} strokeWidth={i===index?2:0}/><title>{label(i)} · {seconds(w.start_ms)}–{seconds(w.end_ms)} · {w.judgment?.attention_risk??'unknown'}</title></g>)}<text x="0" y="211" fill="#9c927f" fontSize="11">0s</text><text x="100%" y="211" textAnchor="end" fill="#9c927f" fontSize="11">{seconds(total)}</text></svg></div></div>{gaps.length>0&&<p className="risk-gap">{gaps.map(g=>seconds(g.start)+'–'+seconds(g.end)).join(', ')} not reviewed</p>}<div className="risk-moments" role="group" aria-label="Choose a reviewed moment">{windows.map((w,i)=><button key={w.end_ms} type="button" className={i===index?'is-selected':''} aria-pressed={i===index} onClick={()=>setSelected(i)}><span>{label(i)} · {seconds(w.start_ms)}–{seconds(w.end_ms)}</span><b>{w.judgment?.attention_risk??'unknown'}</b>{w.validation_issues.length>0&&<small>Check evidence</small>}</button>)}</div>{chosen&&<div className="risk-reason" aria-live="polite"><span>{label(index)}</span><p>{chosen.judgment?shortReason(chosen.judgment.suggestion):chosen.status==='pending'?'Waiting for this moment.':'No validated judgment for this moment.'}</p>{chosen.validation_issues.length>0&&<small>Evidence check needs review. See details.</small>}</div>}</section>;
}
